packaging_format = 2

id = "gossa"
name = "Gossa"
description.en = "Fast and simple webserver for your files"
description.fr = "Serveur web simple et rapide pour vos fichiers"

version = "1.0.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
code = "https://github.com/pldubouilh/gossa"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "You must activate public site if you want to connect a client player to Gossa. This can be changed later via the webadmin."
    help.fr = "Vous devez activer site public si vous souhaitez connecter un lecteur client à Gossa. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        in_subdir = false
        extract = false
        rename = "gossa"
        arm64.url = "https://github.com/pldubouilh/gossa/releases/download/v1.0.0/gossa-linux-arm64"
        arm64.sha256 = "2c1449e5baac8f526b22a8cef0ccf81dc1d6f07bf115da8411a945d3a527db60"
        amd64.url = "https://github.com/pldubouilh/gossa/releases/download/v1.0.0/gossa-linux-x64"
        amd64.sha256 = "09673d9e9aee013fd9b3c0c06102111af792e8fca48913c9c60a445efd0dc314"
        armhf.url = "https://github.com/pldubouilh/gossa/releases/download/v1.0.0/gossa-linux-arm"
        armhf.sha256 = "9fc83341f5ebba5f4804b091760b36bbea99fbc055b1cdd7928a34bd2f1f28db"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "ffmpeg"
