packaging_format = 2

id = "gossa"
name = "Gossa"
description.en = "Fast and simple webserver for your files"
description.fr = "Serveur web simple et rapide pour vos fichiers"

version = "1.1.2~ynh3"

maintainers = []

[upstream]
license = "MIT"
code = "https://github.com/pldubouilh/gossa"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "You must activate public site if you want to connect a client player to Gossa. This can be changed later via the webadmin."
    help.fr = "Vous devez activer site public si vous souhaitez connecter un lecteur client à Gossa. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

    [install.init_post_permission]
    ask.en = "Select which group can create directories, edit and upload files."
    ask.fr = "Choisissez quel groupe peut créer des dossiers, modifier ou ajouter des fichiers."
    help.en = "This can be changed later via the webadmin."
    help.fr = "Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "all_users"

[resources]
        [resources.sources.main]
        in_subdir = false
        extract = false
        rename = "gossa"
        arm64.url = "https://github.com/pldubouilh/gossa/releases/download/v1.1.2/gossa-linux-arm64"
        arm64.sha256 = "e9beb98337ecc8df95015844cd3677f37265d499790b64e2ac1d56634fe6bc30"
        amd64.url = "https://github.com/pldubouilh/gossa/releases/download/v1.1.2/gossa-linux-x64"
        amd64.sha256 = "23a0ae14a59e24d6d652570ff13750be0750e8c491320c76fc49735cd4bb3c69"
        armhf.url = "https://github.com/pldubouilh/gossa/releases/download/v1.1.2/gossa-linux-arm"
        armhf.sha256 = "08d145d8c7c51182ab709059f558416cfd4fc5d0acded8491813056bf62228fa"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "^gossa-linux-arm64$"
        autoupdate.asset.amd64 = "^gossa-linux-x64$"
        autoupdate.asset.armh = "^gossa-linux-arm$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    post.url = "/post"
    post.show_tile = false

    [resources.apt]
    packages = "ffmpeg"
